POST http://localhost:3000/dashboardMinister/agents/1/broadcast HTTP/1.1
content-type: application/json

{
    "msg":"Ceci est un test de vivaDRC pour un envoie multiple",
    "contacts": "[+243979049362]"
}
###
GET http://localhost:3000/dashboardMinister/agents/1 HTTP/1.1

###
GET http://localhost:3000/dashboardMinister/agents HTTP/1.1
